### ISSUE TITLE
Making cgspan start from a given subgraph

### ISSUE THREAD

**Issue by Nojgaard** [NaazS03/cgSpan#3]
Hey all,

I was wondering how difficult it would be to run cgspan with a given starting subgraph, that all closed graphs must contain. Would it be as simple as adding it as a prefix to the dfs_code or would this break the canonicity of said code.

Sincerely,
Nikolai

**Comment by shaulz** [comment]
Hello Nikolai,

I do not think prefixing the dfs_code will work. Closed subgraph will contain many frequent subgraphs whose dfs code is not prefix of a closed subgraph dfs code.
What you can do is as follows:

1. Construct pdfs_edges_projection_list for your subgraph. Basically it is just a list of all projections. Look at _subgraph_mining how backward and forward edges are added.
2. Once cgspan finds all closed subgraphs, for each closed subgraph found, call check_equivalent_occurrence in graph.py with pdfs_edges_projection_list from 1. The result will tell you if closed subgraph includes every occurrence of your subgraph.

If you want to know just about an inclusion but not inclusion of every occurrence, it is enough to call find_possible_isomorphisms in graph.py.

**Comment by Nojgaard** [comment]
Hey Shaul,

Aha, yeah that makes sense. However, in this approach I guess you wont be able to prune branches of your search tree early if they don't include your subgraph. This might just not be possible anyhow I guess.

If I understand step 2 correctly, it is essentially equivalent to looking for a subgraph isomorphism of my subgraph in the closed graph, right?

Thanks again for the very helpful comments!

Sincerely,
Nikolai

**Comment by shaulz** [comment]
Hi Nikolai,

Yes exactly, you have to check isomorphism of your graph into the closed subgraph. I guess you can add prunning branches having dfs code greater than your graph dfs code since they will never lead to a closed subgraph which will include your subgraph.

Thanks,
   Shaul

**Comment by Nojgaard** [comment]
Hey Shaul,

Thanks for the answers, they have been of great help! I will try and see if I can incorporate these changes into a fork. :)

Sincerely,
Nikolai
